### ISSUE TITLE
Rechtsquellen des Kantons Zürich

### ISSUE THREAD

**Issue by laura-bitterli** [maehr/awesome-digital-history#55]
Rechtsquellenportal des StAZH

https://rechtsquellen.sources-online.org/start.html

**Comment by maehr** [comment]
Hi @laura-bitterli thank you very much for your addition. I wonder if the scope of this resource is too narrow. If the cantonal law sources are linked from the national repository I would refrain from adding the regional ones. Do you know if they are linked?
