### ISSUE TITLE
Sammlung Schweizerischer Rechtsquellen online

### ISSUE THREAD

**Issue by laura-bitterli** [maehr/awesome-digital-history#56]
Sammlung Schweizerischer Rechtsquellen online (SSRQ online)

https://editio.ssrq-online.ch
https://www.ssrq-sds-fds.ch/home/

**Comment by maehr** [comment]
Hi laura, can you please extend your addition according to the following template?

```json
{
	"title": "Example",
	"description": "Example description.",
	"url": "http://example.com",
	"region": ["Asia"],
	"language": ["jp"],
	"collection_finished": false,
	"type": ["primary sources", "newspapers", "magazines"],
	"access": ["OA", "online"],
	"reusability": ["copyright", "pd/c0"],
	"period": ["contemporary", "modern"]
}
```

Ps: I will document the contribution process better once we implemented the new version.

**Comment by laura-bitterli** [comment]
{
	"title": "Sammlung Schweizerischer Rechtsquellen online",
	"description": "Retrodigitalisierte und digitale Editionseinheiten der Schweizerischen Rechtsquellen. Ediert wird rechtshistorisches Quellenmaterial vom Mittelalter bis in die Frühe Neuzeit (1798).",
	"url": "https://www.ssrq-sds-fds.ch/projekte/ssrq-online/",
	"region": ["Switzerland", "Cantons"],
	"language": ["de", "fr", "it"],
	"collection_finished": false,
	"type": ["primary sources", "law sources", "edition"],
	"access": ["OA", "online"],
	"reusability": ["copyright", "pd/c0"],
	"period": ["premodern", "early modern", "medieval"]
}

**Comment by maehr** [comment]
Thank you very much. Your contribution will be merged with https://github.com/maehr/awesome-digital-history/pull/59
Best
moritz
