### ISSUE TITLE
\[Addition\]

### ISSUE THREAD

**Issue by henrikehoffmann** [maehr/awesome-digital-history#65]
**Item Details**

Please provide the following details about the item you want to add to the list:

```json
{
	"title": "historicum.net",
	"description": ""historicum.net - Fachinformationsdienst Geschichtswissenschaft" is building up a digital information service covering the entire spectrum of historical scholarship, which complements the basic services provided by university and other academic libraries.",
	"url": "https://www.historicum.net/home/",
	"region": [Germany],
	"language": [de],
	"type": [Newspapers], [magazines], [primary sources], [search engine], tools], [websites], [maps],
	"period": [contemporary], [modern]
}
```

Check [maehr.github.io/awesome-digital-history/](https://maehr.github.io/awesome-digital-history/) for the list of available regions, languages, types, and periods.

**Rationale for the addition**

Briefly explain why you think this item should be added to the list and how it fits the criteria for inclusion.

Die Seite offeriert ein sehr umfassendes Spektrum an Informationen für die historische Forschung in Deutschland. Auch wenn gewisse Dienste eventuell nur für Forschende mit Anbindung an eine Universität in Deutschland hat, gibt es doch genug andere Informationen, die auch für 'ausländische' Forschende von Interesse sein können. 

Please note that this project is released with a [Contributor Code of Conduct](CODE_OF_CONDUCT.md). By participating in this project, you agree to abide by its terms.

**Comment by maehr** [comment]
@koilebeit Do you happen to have time to include this addition?
